config/routes.rb
Rails.application.routes.draw do 
  devise_for :users

  resources :home
  # resources :group_expenses
  
  resources :groups do
    resources :expenses
  end

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get '/unauthorized', to: 'unauthorized#index'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy

  has_one_attached :icon
  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_user
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = @user.groups.all
  end

  # GET /groups/1 or /groups/1.json
  def shows; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = @user.groups.build(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :new, status: :bad_request
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :edit, status: :bad_request
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    if can? :edit, @group
      GroupExpense.where(group_id: @group.id).each do |group_expense|
        expense = group_expense.expense
        group_expense.destroy
        expense.destroy
      end

      if @group.destroy
        redirect_to groups_path, notice: 'Group was successfully deleted'
      else
        flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
        render :index, status: :bad_request
      end
    else
      flash[:alert] = 'Unauthorized'
      redirect_to groups_path
    end
  end

  private

  def find_user
    @user = current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find_by_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<% @groups.each do |group| %>
  <div class="group">
    <div>
      <a href=<%= group_expenses_path(group_id: group.id) %>>
        <% if group.icon.attached?%>
          <%= image_tag(group.icon) %>
        <%else%>
          <%= image_tag('money-chat-group.png') %>
        <%end%>

        <div>
          <h2><%= group.name %></h2>
          <% if Time.now - group.created_at <= 1.minute %>
            <p><%= time_ago_in_words(group.created_at, include_seconds: true) %> ago</p>
          <% elsif Time.now - group.created_at <= 24.hours %>
            <p><%= time_ago_in_words(group.created_at) %> ago</p>
          <% else %>
            <p><%= group.created_at.strftime('%b %d, %Y') %></p>
          <% end %>
        </div>
        </a>
    </div>
    <div class="list_gen">
      <h3>$ <%= group.expenses.sum(:amount) %></h3>
      <div class="btn_list">
        <button class="list_btn"><%= link_to 'Detail', group_path(id: group.id) %> </button>
        <button class="list_btn"><%= link_to 'Expense', group_expenses_path(group_id: group.id) %> </button>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>
<div class="menu">
  <%= render partial: 'partials/menu', locals: { title: 'Edit Group', menu_path: root_path } %>
</div>

<section class="edit_add_page group">
  <%= form_with model: @group, url: group_path(id: @group.id), local: true do |f| %>
    <%= f.text_field :name, autofocus: true %>
    <%= f.file_field :icon %>
    <div class="form-btn">
      <%= f.submit "Update group", class:'list_btn' %>
      <button class="list_btn"> <%= link_to "Back to group", group_path(id: @group.id) %></button>
    </div>
  <% end %>
</section>

app/views/groups/index.html.erb
<div class="menu">
  <%= render partial: 'partials/menu', locals: { title: 'GROUPS', menu_path: root_path } %>
</div>

<section class="groups_page">
  <div>
    <%= render partial: 'group', locals: { groups: @groups } %>
  </div>
  <button class="add_btn"><%= link_to 'Add new group', new_group_path %> </button>
</section>

app/views/groups/new.html.erb
<div class="menu">
  <%= render partial: 'partials/menu', locals: { title: 'ADD NEW GROUP', menu_path: root_path } %>
</div>

<section class="edit_add_page group">
  <%= form_with model: @group, url: groups_path, local: true do |f| %>
    <%= f.text_field :name, autofocus: true, placeholder: "Add Group name" %>
    <%= f.file_field :icon %>
    <div class="form_btn">
      <%= f.submit "Create Group", class: 'list_btn' %>
      <button class="list_btn"><%= link_to "Back", groups_path %></button>
    </div>
  <% end %>
</section>

app/views/groups/show.html.erb
<div class="menu">
  <%= render partial: 'partials/menu', locals: { title: 'GROUP DETAILS', menu_path: root_path } %>
</div>

<section class="group_detail_page">
  <div class="group">
    <div>
      <% if @group.icon.attached?%>
          <%= image_tag(@group.icon) %>
        <%else%>
          <%= image_tag('money-chat-group.png') %>
        <%end%>
      <h1><%= @group.name %></h1>
    </div>

    <div class="list_btn_gen">
      <%= link_to "Edit this group", edit_group_path(@group) %>
      <%= link_to "Back to groups", groups_path %>
      <%= button_to "Destroy this group", @group, method: :delete %>
    </div>
  </div>
<section>